[package]
name = "mical_parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rowan.workspace = true
mical_syntax.workspace = true
